import { ThemeProvider } from '@mui/material'
import Provider from 'client/components/Provider'
import StyledComponentsRegistry from 'client/lib/registry'
import type { Metadata } from 'next'
import { theme } from 'ui/styles'

export const metadata: Metadata = {
  title: '금방하지',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <ThemeProvider theme={theme} >
          <Provider>
            {children}
          </Provider>
          </ThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
